version: "3.8"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react-app.rule=Host(`front.rt.maximizebot.com.br`)"
      - "traefik.http.routers.react-app.entrypoints=websecure"
      - "traefik.http.routers.react-app.tls.certresolver=myresolver"
      - "traefik.http.services.react-app.loadbalancer.server.port=80"
    networks:
      - traefik_net
    restart: unless-stopped

networks:
  traefik_net:
    external: true
