import {
  FaHome,
  FaUsers,
  FaBuilding,
  FaHandshake,
  FaTags,
  FaPercentage,
  FaHandHoldingUsd,
  FaAdjust,
  FaUserPlus,
  FaFileInvoiceDollar,
  FaUserCog,
  FaUserEdit,
  FaListAlt,
  FaMoneyBillAlt,
  FaMoneyCheckAlt,
} from "react-icons/fa";
import { BsBookmarkFill, BsCashCoin } from "react-icons/bs";
import {
  BsFillPersonVcardFill,
  BsFillPersonPlusFill,
  BsBuildings,
  BsBuildingAdd,
  BsTags,
  BsCoin,
  BsCheck2All,
  BsMegaphone,
  BsTrash3,
  BsJournalPlus,
  BsTicketPerforated,
  BsTicketPerforatedFill,
  BsTicketDetailed,
  BsFillClipboard2DataFill,
  BsGraphUp,
  BsPieChartFill,
} from "react-icons/bs";
import { FaFileLines } from "react-icons/fa6";
import { FaUndo } from "react-icons/fa";

export const MENU_IDS = {
  INICIO: "INICIO",
  ASSOCIADOS: "ASSOCIADOS",
  AGENCIAS: "AGENCIAS",
  TRANSACOES: "TRANSACOES",
  OFERTAS: "OFERTAS",
  VOUCHER: "VOUCHER",
  CREDITOS: "CREDITOS",
  EXTRATOS: "EXTRATOS",
  CONTAS: "CONTAS",
  PLANOS: "PLANOS",
  CATEGORIAS: "CATEGORIAS",
  GERENTES: "GERENTES",
  USUARIOS: "USUARIOS",
};

export const menuConfig = [
  {
    id: MENU_IDS.INICIO,
    label: "INÍCIO",
    icon: FaHome,
    stateKey: "home",
    action: { type: "route", value: "/" },
    permissions: {
      menu: [],
    },
  },
  {
    id: MENU_IDS.ASSOCIADOS,
    label: "ASSOCIADOS",
    icon: FaUsers,
    stateKey: "associados",
    action: { type: "modal", value: MENU_IDS.ASSOCIADOS },
    permissions: {
      menu: ["associados.ver", "READ"],
    },
    children: [
      {
        id: "associados.ver",
        label: "Associados",
        route: "/associados",
        icon: FaUsers,
        permissions: ["associados.ver", "READ"],
      },
      {
        id: "associados.listar",
        label: "Lista de Associados",
        route: "/associadosLista",
        icon: BsFillPersonVcardFill,
        permissions: ["associados.listar", "MANAGE_ACCOUNTS"],
      },
      {
        id: "associados.criar",
        label: "Novo Associado",
        route: "/associadosCadastrar",
        icon: BsFillPersonPlusFill,
        permissions: ["associados.criar", "MANAGE_ACCOUNTS"],
      },
    ],
  },
  {
    id: MENU_IDS.AGENCIAS,
    label: "AGÊNCIAS",
    icon: FaBuilding,
    stateKey: "agencias",
    action: { type: "modal", value: MENU_IDS.AGENCIAS },
    permissions: {
      menu: ["agencias.ver", "MANAGE_FRANCHISES", "MANAGE_ACCOUNTS", "ADMIN"],
    },
    children: [
      {
        id: "agencias.ver",
        label: "Lista de Unidades",
        route: "/agencias",
        icon: BsBuildings,
        permissions: ["agencias.ver", "MANAGE_FRANCHISES", "MANAGE_ACCOUNTS"],
      },
      {
        id: "agencias.criar",
        label: "Cadastrar Nova Unidade",
        route: "/agenciasCadastrar",
        icon: BsBuildingAdd,
        permissions: ["agencias.criar", "MANAGE_FRANCHISES", "MANAGE_ACCOUNTS"],
      },
    ],
  },
  {
    id: MENU_IDS.TRANSACOES,
    label: "TRANSAÇÕES",
    icon: FaHandshake,
    stateKey: "transações",
    action: { type: "modal", value: MENU_IDS.TRANSACOES },
    permissions: {
      menu: ["transacoes.ver", "READ"],
    },
    children: [
      {
        id: "transacoes.listar",
        label: "Transações",
        route: "/transacoes",
        icon: BsCoin,
        permissions: ["transacoes.listar", "MANAGE_ACCOUNTS", "transacoes.ver"],
      },
      {
        id: "transacoes.minhas",
        label: "Minhas Transações",
        route: "/transacoesMinhas",
        icon: BsCoin,
        permissions: ["transacoes.minhas", "READ"],
      },
      {
        id: "transacoes.criar",
        label: "Nova Transação",
        route: "/transacoesCadastrar",
        icon: BsCheck2All,
        permissions: ["transacoes.criar"],
      },
      {
        id: "transacoes.estornar",
        label: "Estornar Transação",
        route: "/transacoesExtorno",
        icon: FaUndo,
        permissions: ["transacoes.estornar", "MANAGE_ACCOUNTS"],
      },
    ],
  },
  {
    id: MENU_IDS.OFERTAS,
    label: "OFERTAS",
    icon: FaTags,
    stateKey: "ofertas",
    action: { type: "modal", value: MENU_IDS.OFERTAS },
    permissions: {
      menu: ["ofertas.ver", "READ"],
    },
    children: [
      {
        id: "ofertas.ver",
        label: "Ofertas",
        route: "/ofertas",
        icon: BsTags,
        permissions: ["ofertas.ver", "READ"],
      },
      {
        id: "ofertas.minhas",
        label: "Minhas Ofertas",
        route: "/ofertasMinhas",
        icon: BsMegaphone,
        permissions: ["ofertas.minhas", "READ"],
      },
      {
        id: "ofertas.excluir",
        label: "Excluir Ofertas",
        route: "/ofertasExcluir",
        icon: BsTrash3,
        permissions: ["ofertas.excluir", "MANAGE_ACCOUNTS"],
      },
      {
        id: "ofertas.criar",
        label: "Nova Oferta",
        route: "/ofertasCadastrar",
        icon: BsJournalPlus,
        permissions: ["ofertas.criar"],
      },
    ],
  },
  {
    id: MENU_IDS.VOUCHER,
    label: "VOUCHER",
    icon: FaPercentage,
    stateKey: "voucher",
    action: { type: "modal", value: MENU_IDS.VOUCHER },
    permissions: {
      menu: ["vouchers.ver", "READ"],
    },
    children: [
      {
        id: "vouchers.gerenciar",
        label: "Vouchers",
        route: "/voucher",
        icon: BsTicketPerforated,
        permissions: ["vouchers.gerenciar", "MANAGE_ACCOUNTS"],
      },
      {
        id: "vouchers.meus",
        label: "Meus Vouchers",
        route: "/voucherMeus",
        icon: BsTicketPerforatedFill,
        permissions: ["vouchers.meus", "READ"],
      },
      {
        id: "vouchers.solicitar",
        label: "Solicitar Voucher",
        route: "/voucherCadastrar",
        icon: BsTicketDetailed,
        permissions: ["vouchers.solicitar"],
      },
      {
        id: "vouchers.cancelar",
        label: "Cancelar Voucher",
        route: "/voucherCancelar",
        icon: BsTicketPerforated,
        permissions: ["vouchers.cancelar", "MANAGE_ACCOUNTS"],
      },
    ],
  },
  {
    id: MENU_IDS.CREDITOS,
    label: "CRÉDITOS",
    icon: BsCashCoin,
    stateKey: "creditos",
    action: { type: "modal", value: MENU_IDS.CREDITOS },
    permissions: {
      menu: ["creditos.ver", "READ"],
    },
    children: [
      {
        id: "creditos.meus",
        label: "Meus Créditos",
        route: "/creditosMeus",
        icon: BsFillClipboard2DataFill,
        permissions: ["creditos.meus", "READ"],
      },
      {
        id: "creditos.solicitar",
        label: "Solicitar Crédito",
        route: "/creditosSolicitar",
        icon: BsGraphUp,
        permissions: ["creditos.solicitar"],
      },
      {
        id: "creditos.listar",
        label: "Créditos",
        route: "/creditos",
        icon: BsFillClipboard2DataFill,
        permissions: ["creditos.listar", "MANAGE_ACCOUNTS"],
      },
      {
        id: "creditos.analisar",
        label: "Análise de Créditos",
        route: "/creditosAnalise",
        icon: BsPieChartFill,
        permissions: ["creditos.analisar", "MANAGE_ACCOUNTS"],
      },
      {
        id: "creditos.aprovar",
        label: "Créditos Analisados",
        route: "/cretidosAprovar",
        icon: BsPieChartFill,
        permissions: ["creditos.aprovar", "MANAGE_ACCOUNTS", "ADMIN"],
      },
    ],
  },
  {
    id: MENU_IDS.EXTRATOS,
    label: "EXTRATOS",
    icon: FaFileInvoiceDollar,
    stateKey: "extratos",
    action: { type: "modal", value: MENU_IDS.EXTRATOS },
    permissions: {
      menu: ["extratos.ver", "READ"],
    },
    children: [
      {
        id: "extratos.ver",
        label: "Extratos",
        route: "/estratos",
        icon: FaFileInvoiceDollar,
        permissions: ["extratos.ver", "MANAGE_ACCOUNTS"],
      },
      {
        id: "extratos.meu",
        label: "Meu Extrato",
        route: "/estratosMeus",
        icon: FaFileLines,
        permissions: ["extratos.meu", "READ"],
      },
      {
        id: "extratos.estorno",
        label: "Estornar Extrato",
        route: "/estratosEstorno",
        icon: FaUndo,
        permissions: ["extratos.estorno", "MANAGE_ACCOUNTS"],
      },
    ],
  },
  {
    id: MENU_IDS.CONTAS,
    label: "CONTAS",
    icon: FaHandHoldingUsd,
    stateKey: "contas",
    action: { type: "modal", value: MENU_IDS.CONTAS },
    permissions: {
      menu: ["contas.ver", "financeiro.ver", "MANAGE_ACCOUNTS", "ADMIN"],
    },
    children: [
      {
        id: "financeiro.contasReceber",
        label: "Contas a Receber",
        route: "/contasReceber",
        icon: FaMoneyBillAlt,
        permissions: [
          "financeiro.contasReceber",
          "MANAGE_ACCOUNTS",
          "financeiro.ver",
        ],
      },
      {
        id: "financeiro.contasPagar",
        label: "Contas a Pagar",
        route: "/contasPagar",
        icon: FaMoneyCheckAlt,
        permissions: [
          "financeiro.contasPagar",
          "MANAGE_ACCOUNTS",
          "financeiro.ver",
        ],
      },
    ],
  },
  {
    id: MENU_IDS.PLANOS,
    label: "PLANOS",
    icon: BsBookmarkFill,
    stateKey: "planos",
    action: { type: "modal", value: MENU_IDS.PLANOS },
    permissions: {
      menu: ["planos.ver", "MANAGE_ACCOUNTS", "ADMIN"],
    },
    allowForMatriz: true,
    children: [
      {
        id: "planos.associados",
        label: "Planos Associados",
        route: "/planosAssociados",
        icon: FaListAlt,
        permissions: ["planos.ver", "MANAGE_ACCOUNTS"],
      },
      {
        id: "planos.agencias",
        label: "Planos Agências",
        route: "/planosAgencias",
        icon: FaListAlt,
        permissions: ["planos.ver", "MANAGE_ACCOUNTS"],
      },
      {
        id: "planos.gerentes",
        label: "Planos Gerentes",
        route: "/planosGerentes",
        icon: FaListAlt,
        permissions: ["planos.ver", "MANAGE_ACCOUNTS"],
      },
    ],
  },
  {
    id: MENU_IDS.CATEGORIAS,
    label: "CATEGORIAS",
    icon: FaAdjust,
    stateKey: "categorias",
    action: { type: "modal", value: MENU_IDS.CATEGORIAS },
    permissions: {
      menu: ["categorias.ver", "MANAGE_ACCOUNTS", "ADMIN"],
    },
    allowForMatriz: true,
    children: [
      {
        id: "categorias.ver",
        label: "Categorias",
        route: "/categorias",
        icon: FaListAlt,
        permissions: ["categorias.ver", "MANAGE_ACCOUNTS"],
      },
      {
        id: "categorias.sub",
        label: "Subcategorias",
        route: "/subCategoria",
        icon: FaListAlt,
        permissions: ["categorias.sub", "MANAGE_ACCOUNTS"],
      },
    ],
  },
  {
    id: MENU_IDS.GERENTES,
    label: "GERENTES",
    icon: FaUserPlus,
    stateKey: "gerentes",
    action: { type: "modal", value: MENU_IDS.GERENTES },
    permissions: {
      menu: ["gerentes.ver", "MANAGE_ACCOUNTS", "MANAGE_FRANCHISES", "ADMIN"],
    },
    children: [
      {
        id: "gerentes.criar",
        label: "Novo Gerente",
        route: "/gerentesCadastrar",
        icon: FaUserPlus,
        permissions: ["gerentes.criar", "MANAGE_FRANCHISES"],
      },
      {
        id: "gerentes.lista",
        label: "Gerentes",
        route: "/gerentesLista",
        icon: FaUsers,
        permissions: ["gerentes.ver", "MANAGE_FRANCHISES", "MANAGE_ACCOUNTS"],
      },
    ],
  },
  {
    id: MENU_IDS.USUARIOS,
    label: "USUÁRIOS",
    icon: FaUsers,
    stateKey: "usuarios",
    action: { type: "modal", value: MENU_IDS.USUARIOS },
    permissions: {
      menu: ["usuarios.ver", "MANAGE_ACCOUNTS", "ADMIN"],
    },
    children: [
      {
        id: "usuarios.meusDados",
        label: "Meus Dados",
        route: "/usuariosDados",
        icon: FaUserCog,
        permissions: ["usuarios.meusDados", "READ"],
      },
      {
        id: "usuarios.listar",
        label: "Usuários",
        route: "/usuariosLista",
        icon: FaUsers,
        permissions: ["usuarios.listar", "MANAGE_ACCOUNTS"],
      },
      {
        id: "usuarios.editar",
        label: "Gerenciar Subcontas",
        route: "/usuariosEditar",
        icon: FaUserEdit,
        permissions: ["usuarios.editar", "MANAGE_ACCOUNTS"],
      },
      {
        id: "usuarios.criar",
        label: "Nova Subconta",
        route: "/subcontasCadastrar",
        icon: FaUserPlus,
        permissions: ["usuarios.criar", "MANAGE_ACCOUNTS"],
      },
    ],
  },
];

export const menuConfigMap = menuConfig.reduce((acc, item) => {
  acc[item.id] = item;
  return acc;
}, {});
